project_id = "wdjiwhijjhxjdmsayryk"

[functions.fetch-mandi-prices]
verify_jwt = false

[functions.fetch-all-prices]
verify_jwt = false

[functions.seed-historical-prices]
verify_jwt = false

[functions.seed-all-historical]
verify_jwt = false

[functions.daily-price-cron]
verify_jwt = false

[functions.check-secrets]
verify_jwt = false

[functions.send-telegram-report]
verify_jwt = false
